### ISSUE TITLE
access to content of uploaded files

### ISSUE THREAD

**Issue by NandanaSengupta** [yadudoc/cloud_kotta#27]
It would help avoid errors if users are able to actually view the content of the files uploaded on turing -- either on a new browser tab or in downloadable form. 

Thanks!

**Comment by yadudoc** [comment]
@NandanaSengupta  I've added a download button to the table. Let me know if this works. It isn't very clean from a UI perspective, so if you have ideas on how to make this look clean, please let me know.

**Comment by NandanaSengupta** [comment]
Works! Thanks :)
